router.navigateTo заработал
grafgad/MyApplication2 pull request #1
Opened 2021-09-24 16:11 UTC by grafgad

2021-09-27 15:43 UTC, PeterBukhal-Geekbrains requested changes
Задача не решена.

2021-09-30 10:31 UTC, Rasel579 commented on app/src/main/java/com/example/myapplication2/presenter/AndroidScreens.kt
> +
Сюда нужен метод для перехода на UserFragment,  в аргумент как раз положить конкретного юзера

2021-09-30 10:33 UTC, Rasel579 commented on app/src/main/java/com/example/myapplication2/presenter/IItemView.kt
> +        }
Этот метод getUser(pos : Int)  как раз нужен в классе AndroidScreens

2021-09-30 10:39 UTC, Rasel579 commented on app/src/main/java/com/example/myapplication2/presenter/UsersPresenter.kt
> +//            itemView -> router.navigateTo(getUser())
Вот здесь как раз осуществляется переход на OneUserFragment  с передачей в  bundle либо позиции, либо надо в AndroidScreens пробросить репозитарий, для получения конкретного юзера по его индексу

2021-09-30 10:42 UTC, Rasel579 commented on app/src/main/java/com/example/myapplication2/view/OneUserFragment.kt
>          inflater: LayoutInflater,
Вот здесь как раз через метод bundleOf() можно получить user
companion object {
        private const val ARGS_USER = "ARG_USER"
        fun newInstance(githubUserLogin: String?) = UserFragment().apply {
            arguments = bundleOf(ARGS_USER to githubUserLogin)
        }
    }

2021-10-16 14:40 UTC, merged